name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image frontnend
      with:
        image: kahmed23/serverlessmovies
        tags: frontend-v1, latest
        registry: docker.io
        directory: frontend
        dockerfile: .
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image backend
      with:
        image: kahmed23/serverlessmovies
        tags: backend-v1, latest
        registry: docker.io
        directory: backend
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

        
