name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      name: Check out code
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image frontend
      with:
        image: kahmed23/serverlessmovies
        tags: frontend-v1
        registry: docker.io
        dockerfile: ./frontend/Dockerfile
        directory: frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image backend
      with:
        image: kahmed23/serverlessmovies
        tags: backend-v1
        registry: docker.io
        dockerfile: ./backend/Dockerfile
        directory: backend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      

        
